version: '3.3'

services:
  # django:
  #   build:
  #     context: ./backend
  #   container_name: django
  #   command: >
  #       bash -c "python manage.py migrate && gunicorn teami.wsgi --bind 0.0.0.0:8000"
  #   volumes:
  #     - ./backend:/backend/
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - sqldb
  #   restart: always
    # env_file:
    #   - .env

  sqldb:
    image: postgres:latest
    container_name: sqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=team62
      - POSTGRES_PASSWORD=team62
      - POSTGRES_DB=healthmate
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=team62@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=81
    ports:
     - 8001:81
    volumes:
     - pgadmin_data:/var/lib/pgadmin
    depends_on:
     - sqldb
  
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #   depends_on:
  #     - sqldb
  #   restart: always

volumes:
  db_data:
  pgadmin_data:

  