from django.db import models

class Menu(models.Model):
    name = models.CharField(max_length=128, default="")
    description = models.TextField(default="")
    # day = models.CharField(max_length=2)
    # price = models.DecimalField(max_digits=6, decimal_places=2)
    period = models.CharField(max_length=25, default="")
    containsEggs = models.BooleanField(default=False)
    containsFish = models.BooleanField(default=False)
    containsMilk = models.BooleanField(default=False)
    containsPeanuts = models.BooleanField(default=False)
    containsSesame = models.BooleanField(default=False)
    containsShellfish = models.BooleanField(default=False)
    containsSoy = models.BooleanField(default=False)
    containsTreeNuts = models.BooleanField(default=False)
    containsWheat = models.BooleanField(default=False)
    isGlutenFree = models.BooleanField(default=False)
    isHalal = models.BooleanField(default=False)
    isKosher = models.BooleanField(default=False)
    isVegan = models.BooleanField(default=False)
    isVegetarian = models.BooleanField(default=False)
    calories = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    caloriesFromFat = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    totalFat = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    transFat = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    cholesterol = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    sodium = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    totalCarbohydrates = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    sugars = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    protein = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    vitaminA = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    vitaminC = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    calcium = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    iron = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    saturatedFat = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)                                
    date = models.DateField()
    
    def __str__(self):
        return self.name