# Generated by Django 4.2.10 on 2024-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(default='')),
                ('period', models.CharField(default='', max_length=25)),
                ('containsEggs', models.BooleanField(default=False)),
                ('containsFish', models.BooleanField(default=False)),
                ('containsMilk', models.BooleanField(default=False)),
                ('containsPeanuts', models.BooleanField(default=False)),
                ('containsSesame', models.BooleanField(default=False)),
                ('containsShellfish', models.BooleanField(default=False)),
                ('containsSoy', models.BooleanField(default=False)),
                ('containsTreeNuts', models.BooleanField(default=False)),
                ('containsWheat', models.BooleanField(default=False)),
                ('isGlutenFree', models.BooleanField(default=False)),
                ('isHalal', models.BooleanField(default=False)),
                ('isKosher', models.BooleanField(default=False)),
                ('isVegan', models.BooleanField(default=False)),
                ('isVegetarian', models.BooleanField(default=False)),
                ('calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('caloriesFromFat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totalFat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('transFat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totalCarbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('vitaminA', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('vitaminC', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('calcium', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('iron', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('saturatedFat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('station', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
